package YAY.model;
// Generated Jan 1, 2016 3:43:02 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Kira generated by hbm2java
 */
public class Kira  implements java.io.Serializable {


     private Integer kiraId;
     private Integer kiraUcret;
     private Integer senetSayisi;
     private int kalanSenet;
     private Date baslangicTarihi;

    public Kira() {
    }

	
    public Kira(int kalanSenet, Date baslangicTarihi) {
        this.kalanSenet = kalanSenet;
        this.baslangicTarihi = baslangicTarihi;
    }
    public Kira(Integer kiraUcret, Integer senetSayisi, int kalanSenet, Date baslangicTarihi) {
       this.kiraUcret = kiraUcret;
       this.senetSayisi = senetSayisi;
       this.kalanSenet = kalanSenet;
       this.baslangicTarihi = baslangicTarihi;
    }
   
    public Integer getKiraId() {
        return this.kiraId;
    }
    
    public void setKiraId(Integer kiraId) {
        this.kiraId = kiraId;
    }
    public Integer getKiraUcret() {
        return this.kiraUcret;
    }
    
    public void setKiraUcret(Integer kiraUcret) {
        this.kiraUcret = kiraUcret;
    }
    public Integer getSenetSayisi() {
        return this.senetSayisi;
    }
    
    public void setSenetSayisi(Integer senetSayisi) {
        this.senetSayisi = senetSayisi;
    }
    public int getKalanSenet() {
        return this.kalanSenet;
    }
    
    public void setKalanSenet(int kalanSenet) {
        this.kalanSenet = kalanSenet;
    }
    public Date getBaslangicTarihi() {
        return this.baslangicTarihi;
    }
    
    public void setBaslangicTarihi(Date baslangicTarihi) {
        this.baslangicTarihi = baslangicTarihi;
    }




}


