package YAY.model;
// Generated Jan 1, 2016 3:43:02 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ktarihler generated by hbm2java
 */
public class Ktarihler  implements java.io.Serializable {


     private Integer tarihId;
     private Date odemeTarihi;
     private Integer kiraId;

    public Ktarihler() {
    }

    public Ktarihler(Date odemeTarihi, int kiraId) {
       this.odemeTarihi = odemeTarihi;
       this.kiraId = kiraId;
    }
   
    public Integer getTarihId() {
        return this.tarihId;
    }
    
    public void setTarihId(Integer tarihId) {
        this.tarihId = tarihId;
    }
    public Date getOdemeTarihi() {
        return this.odemeTarihi;
    }
    
    public void setOdemeTarihi(Date odemeTarihi) {
        this.odemeTarihi = odemeTarihi;
    }
    public Integer getKiraId() {
        return this.kiraId;
    }
    
    public void setKiraId(Integer kiraId) {
        this.kiraId = kiraId;
    }




}


