package YAY.model;
// Generated Jan 1, 2016 3:43:02 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ogrenci generated by hbm2java
 */
public class Ogrenci  implements java.io.Serializable {


     private Integer ogrenciId;
     private String ogrenciAd;
     private Integer yatakId;
     private Integer kiraId;
     private Date girisTarihi;
     private String tel;
     private long tc;
     private String resim;

    public Ogrenci() {
    }

	
    public Ogrenci(String tel, long tc, String resim) {
        this.tel = tel;
        this.tc = tc;
        this.resim = resim;
    }
    public Ogrenci(String ogrenciAd, Integer yatakId, Integer kiraId, Date girisTarihi, String tel, long tc, String resim) {
       this.ogrenciAd = ogrenciAd;
       this.yatakId = yatakId;
       this.kiraId = kiraId;
       this.girisTarihi = girisTarihi;
       this.tel = tel;
       this.tc = tc;
       this.resim = resim;
    }
   
    public Integer getOgrenciId() {
        return this.ogrenciId;
    }
    
    public void setOgrenciId(Integer ogrenciId) {
        this.ogrenciId = ogrenciId;
    }
    public String getOgrenciAd() {
        return this.ogrenciAd;
    }
    
    public void setOgrenciAd(String ogrenciAd) {
        this.ogrenciAd = ogrenciAd;
    }
    public Integer getYatakId() {
        return this.yatakId;
    }
    
    public void setYatakId(Integer yatakId) {
        this.yatakId = yatakId;
    }
    public Integer getKiraId() {
        return this.kiraId;
    }
    
    public void setKiraId(Integer kiraId) {
        this.kiraId = kiraId;
    }
    public Date getGirisTarihi() {
        return this.girisTarihi;
    }
    
    public void setGirisTarihi(Date girisTarihi) {
        this.girisTarihi = girisTarihi;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public long getTc() {
        return this.tc;
    }
    
    public void setTc(long tc) {
        this.tc = tc;
    }
    public String getResim() {
        return this.resim;
    }
    
    public void setResim(String resim) {
        this.resim = resim;
    }




}


