package YAY.model;
// Generated Jan 1, 2016 3:43:02 AM by Hibernate Tools 4.3.1



/**
 * Yatak generated by hbm2java
 */
public class Yatak  implements java.io.Serializable {


     private Integer yatakId;
     private Integer odaId;

    public Yatak() {
    }

    public Yatak(Integer odaId) {
       this.odaId = odaId;
    }
   
    public Integer getYatakId() {
        return this.yatakId;
    }
    
    public void setYatakId(Integer yatakId) {
        this.yatakId = yatakId;
    }
    public Integer getOdaId() {
        return this.odaId;
    }
    
    public void setOdaId(Integer odaId) {
        this.odaId = odaId;
    }




}


